### PR TITLE
Update the type of Training phases

### LINKED ISSUE #130: Unable to create training phrases with type: 'TYPE_TEMPALTE'
#### Environment details

  - OS: Ubuntu
  - Node.js version: 10.6.0
  - npm version: 6.1.0
  - `dialogflow` version: 0.50

#### Steps to reproduce

  1. Define Intent with template trainingPhrases :   [{
    type: 'TYPE_TEMPLATE',
    parts: [{text: "I'd like a @size:size pizza"}],
  }]
  2. Create defined Intent: intentsClient.createIntent(Intent)
  3. When define intent with training phrases type: 'TYPE_TEMPLATE' it's still created like type: 
    'TYPE_EXAMPLE'. 
  4. Also this example from github doesn't set training phrase like template: 
   https://github.com/dialogflow/dialogflow-nodejs-client-v2/blob/master/samples/resource.js#L397

Please help me with this case.
Thank you.

### PR DESCRIPTION
**Pull request by madongfly**
Per the Enum name in https://dialogflow.com/docs/reference/api-v2/rest/Shared.Types/Type

Fixes #130 

- [y ] Tests and linter pass
- [y ] Code coverage does not decrease (if any source code was changed)
- [N/A ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by kinwa91** [comment]
👋 @beccca I believe you're lead on DF samples. Could you please review this one?

Fixes #130

**Comment by madongfly** [comment]
Ping~

**Comment by madongfly** [comment]
Ping

**Comment by kinwa91** [comment]
Let's merge this.

**Pull request merged**
